public class Calculator {
    public static Integer adding(Integer num1, Integer num2){
        return num1 + num2;
    }
    public static Integer subtracking(Integer num1, Integer num2){
        return num1 - num2;
    }
    public static Integer multiplying(Integer num1, Integer num2){
        return num1 * num2;
    }
    public static Integer dividing(Integer num1, Integer num2){
        return num1 / num2;
    }
}